### ISSUE TITLE
Enable extraction of spoken-text by 'role' type of character

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-api#105]
The API already facilitates to narrow down **spoken-text** extraction to **gender** and **relation**. The Roman Drama Corpus now features role types (enhancement by us). These are the typical types of Roman comedy, for example:
```xml
<person xml:id="milphidippa" sex="FEMALE" role="ancilla">
  <persName>Milphidippa</persName>
</person>
<person xml:id="palaestrio" sex="MALE" role="servus">
  <persName>Palaestrio</persName>
</person>
<person xml:id="periplectomenus" sex="MALE" role="senex">
  <persName>Periplectomenus</persName>
</person>
<person xml:id="mercurius" sex="MALE" role="deus prologus">
  <persName>Mercurius</persName>
</person>
```
**role** is a standard [attribute according to the TEI guidelines](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-person.html). In this case we also allow multiple values, as is shown by the **mercurius** example, a character which serves as both **deus** and **prologus**.

The proposition is to allow narrowing down the extraction of spoken-text to these role types, the attribute function can be called **role**. This will allow for a comparative analysis of linguistic properties of different role types.

NB. The French corpus will have this attribute as well, even if it is called (in French) **statut**. Cf. [this randomly chosen play](http://www.theatre-classique.fr/pages/documents/ABEILLE_LYNCEE.xml).

**Comment by cmil** [comment]
A new version (v0.73.0) of the API has been deployed to staging.dracor.org that implements text extraction by role. See above PR and the following examples:

https://staging.dracor.org/api/corpora/rom/play/plautus-amphitruo/spoken-text?role=ancilla
https://staging.dracor.org/api/corpora/rom/play/plautus-amphitruo/spoken-text-by-character

@lehkost Please test.
