### ISSUE TITLE
Dockerize DraCor API

### ISSUE THREAD

**Issue by cmil** [dracor-org/dracor-api#110]
The DraCor API currently comprises three individual services:

- an eXist DB with `dracor` package at its core
- a [Jena Fuseki](https://jena.apache.org/documentation/fuseki2/) SPARQL server
- the [dracor-metrics](https://github.com/dracor-org/dracor-metrics) service

Any instance of the DraCor API only works as a combination of these three services. While we partly managed it with ant targets in the past, setting up a local development environment is still somewhat tedious. Providing a multi-container [Docker Compose](https://docs.docker.com/compose/) setup could streamline this process. It could even allow researchers and non-developers to easily run their own instance of the API locally.

**Comment by ingoboerner** [comment]
https://github.com/dracor-org/dracor-api/tree/110-dockerize-dracor-api

as a start. Added two files (devDockerfile and a compose). Should work:

`docker-compose -f docker-compose.dev.yml build`
`docker-compose -f docker-compose.dev.yml up`

eXist will run on localhost:9099

**Comment by cmil** [comment]
@ingoboerner cool! I created a pull request. That makes it easier to work on it.

**Comment by ingoboerner** [comment]
I set up a repository containing only the docker-stuff here: https://github.com/dracor-org/dracor-docker/tree/develop
