### ISSUE TITLE
spoken-text-by-character: <sp> is split by <stage>

### ISSUE THREAD

**Issue by IraPS** [dracor-org/dracor-api#117]
When requesting spoken text by character, if there is a stage direction (\<stage\>) within the \<sp\>, the spoken text is split into parts and returned as two separate strings. For example, in the Russian corpus "ostrovsky-groza":

TEI:
```
<sp who="#feklusha">
                <speaker>Феклуша.</speaker>
                <p>А я, матушка, так своими глазами видела; конечно, другие от суеты не видят ничего,
                так он им машиной показывается, они машиной и называют, а я видела, как он лапами-то
                вот так</p>
                <stage>(растопыривает пальцы)</stage>
                <p>делает. Ну, и стон, которые люди хорошей жизни, так слышат.</p>
              </sp>
```

What API returns as spoken text for this \<sp\>:

> 'А я, матушка, так своими глазами видела; конечно, другие от суеты не видят ничего, так он им машиной показывается, они машиной и называют, а я видела, как он лапами-то вот **так', 'делает.** Ну, и стон, которые люди хорошей жизни, так слышат.'

You can see that the sentence is interrupted, the sentence is unfinished and it looks like there's another speech act that starts with a lowercase letter, while, in fact, it's part of the sentence in the previous string.

The preferred output would be to not split it into two parts by the stage direction, but have it as a single string that corresponds to this single speech act (the content of \<sp\>):

> 'А я, матушка, так своими глазами видела; конечно, другие от суеты не видят ничего, так он им машиной показывается, они машиной и называют, а я видела, как он лапами-то вот так делает. Ну, и стон, которые люди хорошей жизни, так слышат.'

**Comment by IraPS** [comment]
I've just realised that it might be not a bug but an error in the mark-up:
```
вот так</p>
<stage>(растопыривает пальцы)</stage>
<p>делает.
```
I guess there shouldn't be a `</p>` "break" here, because in other cases like this one it's not there. See, for example, a part of another `<sp>` that has no `<p>` "break" before `<stage>`:

```
А смерть не приходит. Ты ее кличешь, а она не приходит. Что ни увижу, что ни услышу, только тут
<stage>(показывая на сердце)</stage>
больно. 
```

**Comment by lehkost** [comment]
Ok, I fixed the markup for "Groza" to align it with our source (ilibrary.ru), see https://github.com/dracor-org/rusdracor/commit/b70d0879799c1a36c6d91a016d536c0d56be59d4. However, some of these breaks still exist, also in line with the original, see this example:
```xml
<sp who="#kabanova">
  <speaker>Кабанова.</speaker>
  <p>Поди, Феклуша, вели приготовить закусить что-нибудь.</p>
  <stage>Феклуша уходит.</stage>
  <p>Пойдем в покои!</p>
</sp>
```
Generally, in this source, if a stage direction is put between brackets, it's part of the running line. If a stage direction comes without brackets, it gets its own line.

But I think we can close this ticket now.
