### ISSUE TITLE
Deliver alternative languages for (sub)titles of plays and character names

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-api#118]
The Russian corpus has both, Cyrillic (sub)titles and English versions/translations of (sub)titles, [example](https://github.com/dracor-org/rusdracor/blob/master/tei/bulgakov-dni-turbinyh.xml#L7):

```xml
<titleStmt>
  <title type="main">Дни Турбиных</title>
  <title type="main" xml:lang="eng">The Days of the Turbins</title>
  <title type="sub">Пьеса в четырех действиях</title>
  <title type="sub" xml:lang="eng">A Play in Four Acts</title>
  <author key="wikidata:Q835">Булгаков, Михаил Афанасьевич</author>
</titleStmt>
```
We want to add Greek/English titles also to GreekDraCor and possible other corpora (GerDraCor: German+English?). I'm not sure on which level the API delivers title strings (at least not in the [metadata](https://dracor.org/api/corpora/rus/metadata) file).

If available, could we deliver alternative titles through the API so that they can also be included on the website? The rule could be like this: IF there is a second title or subtitle with a language attribute different than the TEI root element, THEN make it available through the API (with the appropriate language attribute as marker).

**Comment by cmil** [comment]
@lehkost titles are provided in both the corpus listing (e.g. https://dracor.org/api/corpora/rus) and the play info (e.g. https://dracor.org/api/corpora/rus/play/gogol-revizor).

Could the alternative title or subtitle be in any other language then English? I would assume not. And in that case I would suggest to provide the alternatives as `titleEn` and `subtitleEn` when available. Similarly there could be a `nameEn` or `fullnameEn` in the `authors` array when English name forms are provided in the TEI documents.

**Comment by lehkost** [comment]
For the time being, English titles would be most important. I wouldn't exclude the possibility to add titles in (a few) other languages, like German, though (we also provide German character names for RusDraCor, for example).

But titleEN and subtitleEN would be okay. If we decide to add other languages, we can easily use titleDE or something, but this is not pressing.

So, +1 to adding titleEN, subtitleEN, nameEn, fullnameEn if available.

**Comment by cmil** [comment]
@lehkost The above changes are now deployed on staging.dracor.org. Could you test them a bit?

**Comment by lehkost** [comment]
In ```https://staging.dracor.org/api/corpora/rus```, a play looks like this:

![author-authors](https://user-images.githubusercontent.com/6539515/127743052-0e9f1a63-b56c-45a1-a2cf-12b35741eadb.png)

Is this correct, having appear ```author``` *and* ```authors```?

**Comment by cmil** [comment]
Yes, `author` is the deprecated single value field that we keep carrying around in order to not break the shiny app.
