### ISSUE TITLE
Add genre information to metadata of plays

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-api#120]
After deciding on a mark-up strategy for genre declaration (https://github.com/dracor-org/dracor-schema/issues/3), we are ready to add this info to the metadata of plays in a unified manner for all corpora. For the time being we only mark genre very coarsely on two levels:
### comedy or tragedy:
```xml
<textClass>
  <keywords>
    <term type="genreTitle">Comedy</term>
  </keywords>
  <classCode scheme="http://www.wikidata.org/entity/">Q40831</classCode>
</textClass>
```
or
```xml
<textClass>
  <keywords>
    <term type="genreTitle">Tragedy</term>
  </keywords>
  <classCode scheme="http://www.wikidata.org/entity/">Q80930</classCode>
</textClass>
```
### libretto or not:
```xml
<textClass>
  <keywords>
    <term type="genreTitle">Libretto</term>
  </keywords>
  <classCode scheme="http://www.wikidata.org/entity/">Q131084</classCode>
</textClass>
```
The API should add two columns to the metadata files:
1. Genre (```Comedy```, or ```Tragedy```, or ```empty``` if no information is available).
2. Libretto (```1``` for yes, this is a libretto, and ```0``` for no, this is not a libretto).

The background for this feature is:
1. A very general distinction between the two main genres tragedy and comedy to be able to automatise analyses like [this one](https://dlina.github.io/Network-Values-by-Genre/).
2. An automatised possibility to exclude libretti from an analysis (or to just assemble libretti for an analysis).

The German corpus already has some files with corresponding markup to test this feature once it's implemented (see https://github.com/dracor-org/gerdracor/commit/98b713bebbd47d8b024c07db62eafe0150a856a1).

**Comment by lehkost** [comment]
Update: GerDraCor was fully marked up with basic genre information as described above (see https://github.com/dracor-org/gerdracor/commit/9c2fcf55cce2ec6290ffc8615e98d9b2355707d9). So we could test the new function with this corpus first…

**Comment by cmil** [comment]
@lehkost How do we deal with corpora that have `textClass` defined but do not conform to the new markup strategy, e.g. RusDraCor? I would suggest to look for a `//textClass/classCode[@scheme = "http://www.wikidata.org/entity/]` and, if the Wikidata ID provided matches one of the three mentioned above, set the `genre` and `libretto` fields respectively. Non matching `textClass`es would be ignored. 

Regarding the `libretto` field, I would  set it to `true` if there is a matching `textClass` with the libretto class code. If the `textClass/classCode` is specified but is not a libretto I set it to `false`. If there is no `textClass/classCode` I'd leave the `libretto` field empty.

**Comment by lehkost** [comment]
Speaking of which, RusDraCor will be updated with proper genre info in the next hour. 🙃

And I agree to your suggestion how to handle ```textClass```, let's only match Wikidata IDs of genres as described above.

**Comment by cmil** [comment]
@lehkost Implemented in v0.75.0 deployed on staging. Please test!

**Comment by lehkost** [comment]
Works well for GerDraCor, metadata loaded into LibreOffice Calc:

![genre-screenshot](https://user-images.githubusercontent.com/6539515/101258332-1bd08c00-3722-11eb-952d-4dd5b6edf597.png)

The only thing I would change is the handling of Libretto. The assignment of "true" is okay, but every play that has no "Libretto" indication should generally be "false", also those plays that have no other genre information. Reason: If "Libretto" information is not marked up it means that a play is not a libretto.

**Comment by lehkost** [comment]
I just added "Tragicomedy" to GerDraCor where appropriate, like this:
```xml
<textClass>
  <keywords>
    <term type="genreTitle">Tragicomedy</term>
  </keywords>
  <classCode scheme="http://www.wikidata.org/entity/">Q192881</classCode>
</textClass>
```

**Comment by cmil** [comment]
> I just added "Tragicomedy" to GerDraCor where appropriate, like this:
> ...

Is the idea that repertoire of accepted text classes will grow over time or will it even be completely open to additions? This has implication on how the libretto flag is implemented. I assumed that for now Tragedy, Comedy and Libretto were the only supported text classes.

**Comment by lehkost** [comment]
Ideally, the text classes (genres) will grow over time. Tagging genre for such diverse corpora in a TEI document, though, is not the best solution. We might build on a drama genre ontology in the future, but there is no good candidate there yet.

For now I would say we have two levels of genre information: 1. libretto or not; 2. tragedy, comedy or tragicomedy, if applicable. The later group under (2.) might grow in the near future, the first group (1.) probably won't, because it just tells apart libretti and dramas not written for music. I hope that makes sense?

**Comment by cmil** [comment]
So for libretti there will never be a chance to distinguish between e.g. dramma giocoso, tragédie lyrique, Singspiel etc.? That looks like an unnecessary restriction to me.

Be that as it may, the current implementation (see commit above) exclusively uses the `classCode` element to determine the genre and completely ignores the `textClass/keywords` entirely. Instead it introduces a [map of recognised class codes](https://github.com/dracor-org/dracor-api/blob/73747be4d914a555a4e74698e8f9683f899fe32d/modules/config.xqm#L76). If any of these codes, except the one for libretto, has been attributed to a play, the respective label (currently `Tragedy`, `Comedy` or `Tragicomedy`) will be assigned to the `genre` field. If more than one of the recognised codes have been assigned the label of the first one will be used as `genre`.

This implementation has the following advantages:

1. It allows for text classes other than the recognised ones to be attributed to a play without interfering with the genre attribution.
2. It even allows a genre to be assigned to a libretto. (Whether this makes sense scientifically is outside the scope of this implementation.)
3. Ignoring the keywords makes it unnecessary to ensure that the `keyword` and `classCode` are consistent. (As an aside, the [TEI documentation](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/HD.html#HD43) does not seem to imply any defined relationship between `textClass/keywords` and `textClass/classCode` other than a shared `taxonomy`, which in the currently used markup is not provided.)

It may seem as a disadvantage that the map of recognised class codes needs to be updated, if we want to add a new text class relevant for genre attribution. One could also see it as an easy was to control what DraCor considers a genre.

Please test and let me know if this makes sense. If so, we should probably document this somewhere.

**Comment by lehkost** [comment]
Good points! Ideally, we would like to store all genre info we can gather on each play, including the libretto subgenres you mention. The way we started to implement genre markup now doesn't prevent us to further differentiate genre in the future.

On a sidenote, some examples from the emerging French Drama Corpus:
```xml
<textClass>
  <keywords>
    <term type="genreTitle">Tragédie</term>
    <term type="genreTitle">vers</term>
  </keywords>
</textClass>
```
```xml
<textClass>
  <keywords>
    <term type="genreTitle">Comédie</term>
    <term type="genreTitle">prose</term>
  </keywords>
</textClass>
```
```xml
<textClass>
  <keywords>
    <term type="genreTitle">Monologue</term>
    <term type="genreTitle">vers</term>
  </keywords>
</textClass>
```
```xml
<textClass>
  <keywords>
    <term type="genreTitle">Proverbe</term>
    <term type="genreTitle">prose</term>
  </keywords>
</textClass>
```
Also here, Tragedy, Comedy, Monologue and Proverb are not on the same level of attributing a genre, the same way as "prose" and "verse" are a different way of (a much more formal) genre description. We should probably try not to loose any of the information we inherit from other sources (and should try to add rich genre markup for the sources that don't have any).

**Comment by cmil** [comment]
I would suggest that the [transformation script for dracor-org/fredracor](https://github.com/dracor-org/fredracor/blob/55e2b63b9f68d8f3107b72dd3f0649c04b8b42a8/transform.xq#L777) adds the appropriate `classCode` where genre information found in the originals matches the recognised text classes defined in #122.
