### ISSUE TITLE
Offer relation data in GraphML format

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-api#121]
We already offer co-occurrence data in GraphML format, we should offer relation data in the same format, too. It would directly serve our rdracor library since GraphML is directly usable with the igraph library that we use.

**Comment by cmil** [comment]
This has now been implemented and deployed to staging. See for example https://staging.dracor.org/api/corpora/ger/play/gottsched-atalanta/relations/graphml. @lehkost Please test!

**Comment by lehkost** [comment]
Thanks! I think it works as it should, see the example file rendered with Cytoscape:
![example-graphml-cytoscape](https://user-images.githubusercontent.com/6539515/102019625-e0167180-3d74-11eb-9b4a-f1eb297d131b.png)
I think this can go live!

**Comment by Pozdniakov** [comment]
is it possible to have relation data in one GraphML to avoid further merging? Like:

```
<edge id="1" directed="false" source="amaryllis" target="atalanta">
<data key="weight">5</data>
<data key="relation">siblings</data>
</edge>
```

Either inside `/corpora/{corpusname}/play/{playname}/networkdata/graphml` command or inside separate command.

**Comment by lehkost** [comment]
I can understand the need, and if we implement this separately, I think we should probably re-organise all the network data more meaningfully, like this:

* /networkdata-cooccurrence/csv
* /networkdata-cooccurrence/gexf
* /networkdata-cooccurrence/graphml
* /networkdata-relations/csv
* /networkdata-relations/gexf
* /networkdata-relations/graphml
* /networkdata-cooccurrence-incl-relations/csv
* /networkdata-cooccurrence-incl-relations/gexf
* /networkdata-cooccurrence-incl-relations/graphml

Something like this?

**Comment by cmil** [comment]
Wouldn't combining coocurrences and relations actually be misleading in some cases? Theoretically there could be related characters that never occur on stage together.

**Comment by lehkost** [comment]
These are my concerns, too.

But by opening a third option for a merged cooccurrence plus relations network data type by letting the other two options as they are, we should be fine. And technically, if two characters are related (kinship or similar), but have no occurrence together, the weight of their relationship would be "0". Then the choice of visualising this (or calculating with that data) would fall back to the user.

Agree to opening a new ticket on this (can we move Vanya's initial question to a new issue?).
