### ISSUE TITLE
Extract text within <spGrp> in its original context

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-api#132]
```<spGrp>``` (= speech groups, cf. [TEI Guidelines](https://www.tei-c.org/release/doc/tei-p5-doc/de/html/ref-spGrp.html)) allow to encode different spoken text bits uttered by several characters at the same time. An example in the wild is here, [top of p. 38](https://books.google.com/books?id=hOtRhHivrfQC&pg=PA38).

The corresponding play in DraCor is here:
[Johann André: Der Comödienfeind](https://dracor.org/id/ger000525) (1765)

This passage is encoded as recommended by the guidelines and also accepted by our DraCor schema (see [TEI version of the play](https://dracor.org/api/corpora/ger/play/andre-der-comoedienfeind/tei)).

When extracting the spoken text via our API – https://dracor.org/api/corpora/ger/play/andre-der-comoedienfeind/spoken-text – the text is extracted correctly, but put at the end of the main text, probably a problem of XML tree hierarchy.

My suggestion is to extract texts from within ```<spGrp>``` in their original contexts.

**Comment by cmil** [comment]
I cannot reproduce this. Both https://dracor.org/api/corpora/ger/play/andre-der-comoedienfeind/spoken-text and https://staging.dracor.org/api/v1/corpora/ger/plays/andre-der-comoedienfeind/spoken-text seem to put the lines 

> Was soll das heisen!
> Was ist das!

in the correct context. Am I missing something, @lehkost?

**Comment by lehkost** [comment]
Hi @cmil, thanks for checking, I can't reproduce this either any more. This seems to have solved itself somehow in the past 2,5 years. 😊 Unfortunately, I didn't take a screenshot or saved the file back then. So let's close this one.
