### ISSUE TITLE
New endpoint /character/{wikidata-id}

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-api#144]
After implementing https://github.com/dracor-org/dracor-api/issues/143, we can create an endpoint collecting all plays **across corpora** including a mythological or historical character (if Wikidata ID is provided).

**Comment by lehkost** [comment]
The goal would be to receive a list with DraCor IDs throughout all corpora, the question is if this is doable in real time. E.g., ```/character/Q76918``` would return all plays with a character based on the historic Faust, like:
* https://dracor.org/id/ger000014
* https://dracor.org/id/ger000072
* https://dracor.org/id/ger000561
* …

Another example: ```/character/Q131412``` (Maria Stuart)
* https://dracor.org/id/ger000311
* https://dracor.org/id/ita000009
* …

**Comment by cmil** [comment]
The above PR implements an endpoint returning a list of JSON objects providing ID, title, author(s) of plays with the given character. It has been deployed on staging.dracor.org. See for example https://staging.dracor.org/api/character/Q76918.
