### ISSUE TITLE
docker-compose build fails due to invalid settings in the metrics-part

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-api#167]
There is an issue when building from the docker-compose for the first time, that @peertrilcke reported:

<img width="1109" alt="docker-compose-build-error" src="https://user-images.githubusercontent.com/12182347/180151769-c281ed1b-8f1b-471f-b43d-61d54e2c992a.png">

I assume, it's somehow related to this line:
https://github.com/dracor-org/dracor-api/blob/main/docker-compose.yml#L27
`build: https://github.com/dracor-org/dracor-metrics.git#main`

I suppose, it could be `image:` . A solution would be to offer a pre-build image of the metrics service and push to a repository, then the compose build could pull the image from somewhere.

**Comment by peertrilcke** [comment]
docker-compose version 1.11.2, build dfed245

**Comment by peertrilcke** [comment]
no error message using docker-compose version 1.29.2, build 5becea4c

**Comment by ingoboerner** [comment]
I can run `docker-compose build --no-cache` wich works for me

**Comment by ingoboerner** [comment]
> no error message using docker-compose version 1.29.2, build 5becea4c

Great!
