### ISSUE TITLE
Clearing fuseki doesn't work in local Docker setup

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-api#173]
To debug the DTS endpoints I set up a local DraCor environment based on docker-compose and the DTS branch. I can connect to the empty exist and to the dracor api, but loading of corpora fails (probably due to fuseki):

```
api_1       | (Line: 467 /db/apps/dracor/modules/rdf.xqm) clearing fuseki graph: http://dracor.org/ger
```
The loading doesn't proceed after this line.

**Comment by ingoboerner** [comment]
as a quickfix I uncommented here in load.xqm: https://github.com/dracor-org/dracor-api/blob/dts/modules/load.xqm#L105

```
(: clear fuseki graph :)
-            drdf:fuseki-clear-graph($name),
+            (: drdf:fuseki-clear-graph($name), :)
```

**Comment by cmil** [comment]
@ingoboerner I now created a slimmed down version of stain/jena-fuseki (https://github.com/dracor-org/dracor-fuseki) and integrated it into the docker-compose.yml of #175. Could you try that and see if it works for you?
