### ISSUE TITLE
get base url of running instance

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-api#174]
In the DTS module I need to generate the URL of the API endpoint, that allows for downloading the TEI. It is hardcoded at the moment: https://github.com/dracor-org/dracor-api/blob/dts/modules/dts.xqm#L38

It is included in the response object returned by the DTS collection endpoint; see key `dts:download`:

```
{
    "@context": {
        "@vocab": "https://www.w3.org/ns/hydra/core#",
        "dc": "http://purl.org/dc/terms/",
        "dts": "https://w3id.org/dts/api#"
    },
    "dts:passage": "/api/dts/documents?id=ger000088",
    "dts:references": "/api/dts/navigation?id=ger000088",
    "@type": "Resource",
    "totalItems": 0,
    "dts:totalParents": 1,
    "title": "Emilia Galotti",
    "dts:dublincore": {
        "dc:creator": "Lessing, Gotthold Ephraim",
        "dc:language": "ger"
    },
    "dts:citeDepth": 3,
    "dts:download": "https://staging.dracor.org/api/corpora/ger/play/lessing-emilia-galotti/tei",
    "@id": "ger000088",
    "dts:totalChildren": 0,
    "dts:citeStructure": [
        {
            "dts:citeType": "front",
            "dts:citeStructure": []
        },
        {
            "dts:citeType": "body",
            "dts:citeStructure": [
                {
                    "dts:citeType": "act",
                    "dts:citeStructure": [
                        {
                            "dts:citeType": "scene"
                        }
                    ]
                }
            ]
        }
    ]
}
```

Is there a way to retrieve the base url via an util function?

**Comment by ingoboerner** [comment]
it seems to be defined in the `config.xqm`; but also hardcoded here:

`declare variable $config:api-base := "https://dracor.org/api";`
there is already a FIXME:

> FIXME: This should be determined dynamically using request:get-*() functions.
  However the request object doesn't seem to be available in a RESTXQ context.

https://github.com/dracor-org/dracor-api/blob/main/modules/config.xqm#L40

Maybe we could pass this URL as an environment variable ENV (?) in the Docker build?

**Comment by cmil** [comment]
@Ingo You should use `$config:api-base`. In #175 I'll make this configurable, so in future dracor-api versions this variable should provide the correct base URI.
