### ISSUE TITLE
is there a way to get wikidata ID of a play through the API?

### ISSUE THREAD

**Issue by DanilSko** [dracor-org/dracor-api#178]
Hi there! 
Recently in our research we needed to check some wikidata info on FreDraCor and GerDraCor plays. For most of our analyses we used API via pydracor and it was working well. But in this case we did not find any way to get the wikidata ID's of plays through the API. So we resorted to cloning the repo and getting the data directly from the XML-s. Did we miss something?

**Comment by lehkost** [comment]
Oh, it seems this is a well-spotted gap in our metadata delivery via our API. If I'm not missing something here (@cmil) and we *do* have a function somewhere that delivers Wikidata IDs, then I'd suggest to add a column/field to the metadata files (csv & json). Name of the column/field could be "wikidataId". The value could either be just the Q number or the full Wikidata URI that we provide in the TEIs.
