### ISSUE TITLE
add information on license to repository

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-api#183]
Could we maybe add the information on the license is the api-code to the repo?

**Comment by cmil** [comment]
Yes, we should. MIT? @lehkost

**Comment by lehkost** [comment]
sure, i don't see any reason against MIT

**Comment by cmil** [comment]
There seems to have been some discussion about licensing on Mattermost, @peertrilcke. Did this point also into the MIT direction?

**Comment by peertrilcke** [comment]
hm, I wouldn't say that this discussion already has a direction ..

**Comment by cmil** [comment]
Solved in a3fa91834bca2cc0b9b9af540bccf37c5e485955.
