### ISSUE TITLE
RDF `sameAs` Wikidata URL appears for plays without a Wikidata ID

### ISSUE THREAD

**Issue by v-ji** [dracor-org/dracor-api#190]
Plays without a Wikidata ID nonetheless carry the following statement in their RDF representation:

```xml
<owl:sameAs rdf:resource="http://www.wikidata.org/entity/"/>
```

This example is from [Agradecer y no amar](https://dracor.org/id/cal000056).

A SPARQL query results in 1531 such cases:
```
SELECT * FROM <urn:x-arq:UnionGraph> WHERE {
  ?play <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type.
  FILTER (?type = <http://dracor.org/ontology#play>).

  ?play <http://www.w3.org/2002/07/owl#sameAs> ?sameAs.
  FILTER (str(?sameAs) = "http://www.wikidata.org/entity/").
}

# Showing 1 to 50 of 1,531 entries (in 0.137 seconds)
```

This statement should probably be omitted for plays without a Wikidata ID.

**Comment by ingoboerner** [comment]
RDF generation is work in progress, wouldn't use it/rely on it at the moment. I will rewrite it but not in xQuery.
