### ISSUE TITLE
Enhance OpenAPI

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-api#194]
as briefly discussed at some other place the OpenAPI Specification of the API could be restructured/enhanced, e.g.

* Add schemas of responses
*  Review response examples, e.g. /corpora: missing key "acronym"
* Tags could better reflect functionality of the API (see #192)
> Technically, I think, the groups are "Tags", right? So you can assign multiple tags to an endpoint which would result in making it show up in several of these groupings. IMHO, it would make sense to introduce more of these, e.g. group endpoints that provide the data for Network Analysis,...
> I'm all for improving the readability of the OpenAPI documentation by giving it a clear structure. Maybe we should think about replacing the "public" tag by one or more tags that better serve this purpose then.
* Requirement to log in for admin operations could be captured in a machine readable way, e.g. "Security Scheme Object"

**Comment by cmil** [comment]
I split this up into individual issues, closing this.
