### ISSUE TITLE
Missing numPersonGroups in metadata CSV (via API)

### ISSUE THREAD

**Issue by lucagiovannini7** [dracor-org/dracor-api#198]
Found this issue while working with a local DraCor istance via Docker (@ingoboerner), but it happens also with “official” DraCor corpora.

See e.g. the Roman Corpus. Several plays have one or more collective characters, as it could be seen [here](https://dracor.org/api/corpora/rom/metadata), but when downloading the CSV metadata file via [this API call](https://dracor.org/api/corpora/rom/metadata/csv) the _NumPersonGroups_ column is empty.

Could it be because of the mismatch between the names of the columns (_num**Of**PersonGroups_ in the online JSON metadata file, _numPersonGroups_ in the downloaded CSV)?

Any idea on how to recover the data?

**Comment by cmil** [comment]
This has been fixed in [0.90.1](https://github.com/dracor-org/dracor-api/releases/tag/v0.90.1) which has been deployed to staging.dracor.org but not yet to dracor.org.

**Comment by ingoboerner** [comment]
@lucagiovannini7 you would probably have to change the image (which we don't have for any other than `ingoboerner/dracor-api:v0.86.3_local` here: https://github.com/ingoboerner/stable-dracor/blob/master/docker-compose.empty.yml#L3
