### ISSUE TITLE
Remove section "Atom integration" in readme

### ISSUE THREAD

**Issue by afuetterer** [dracor-org/dracor-api#204]
Hi,

maybe you should discourage users from using the Atom editor, which is discontinued by GitHub.
See: https://github.blog/2022-06-08-sunsetting-atom/

Is this perhaps comparable?
https://marketplace.visualstudio.com/items?itemName=eXist-db.existdb-vscode

**Comment by cmil** [comment]
@afuetterer Yes, the VS code extension is the modern replacement of the Atom integration. I'v been using this for a long time. The documentation will be fixed accordingly in v1 of dracor-api.
