### ISSUE TITLE
Issues with OpenAPI specification

### ISSUE THREAD

**Issue by afuetterer** [dracor-org/dracor-api#205]
Hi,

there are some issues with the OpenAPI specification in https://github.com/dracor-org/dracor-api/blob/v1/api.yaml.

# Context
I am sitting in the DraCor Onboarding Workshop and trying to break your API, i.e. testing the API schema, with permission of @lehkost. I am not an attacker. :)

I am using the Python library [schemathesis](https://schemathesis.readthedocs.io/). Another popular framework would be [dredd](https://github.com/apiaryio/dredd).

```console
$ pip install schemathesis
$ schemathesis run https://staging.dracor.org/api/openapi.yaml
```

Storing and replaying test cases
https://schemathesis.readthedocs.io/en/stable/cli.html#storing-and-replaying-test-cases

```console
$ schemathesis run --cassette-path cassette.yaml https://staging.dracor.org/api/openapi.yaml
```

# Findings

- #206 
- #207 
- #208 
- #209 

## /id/{id}
There is no response 200 defined, only 303 and 404
https://github.com/dracor-org/dracor-api/blob/82dd3d4193f44a64d29207ec99bff45b10734545/api.yaml#L1008-L1009

## 400
- https://staging.dracor.org/api/corpora/%00
- https://staging.dracor.org/api/wikidata/author/%00

# Notes

https://schemathesis.readthedocs.io/en/stable/how.html#payload-serialization
https://schemathesis.readthedocs.io/en/stable/cli.html#storing-and-replaying-test-cases

**Comment by ingoboerner** [comment]
The id endpoint only issues a redirect depending on the accept header. 303 is the right status code. See specifications on "cool uris". It is also explained in our report On Programmable Corpora

**Comment by afuetterer** [comment]
Hi, I am testing the API during the DraCor workshop and will post a few more examples. Alright?

Please feel free to ignore. :)

**Comment by afuetterer** [comment]
> The id endpoint only issues a redirect depending on the accept header. 303 is the right status code. See specifications on "cool uris". It is also explained in our report On Programmable Corpora https://zenodo.org/record/7664964 p33

Can you give me a curl example with the correct HTTP header please?

**Comment by cmil** [comment]
>> The id endpoint only issues a redirect depending on the accept header. 303 is the right status code. See specifications on "cool uris". It is also explained in our report On Programmable Corpora https://zenodo.org/record/7664964 p33
>>
> Can you give me a curl example with the correct HTTP header please?

As stated in the `/id/{id}` endpoint description, you can specifically request either the JSON or RDF representation by sending the  `Accept` header with the respective type. Any request with another `Accept` header or none at all will be redirected to web page of the play. See:

```sh
curl -i -H 'Accept: application/json'  https://staging.dracor.org/id/ger000001
curl -i -H 'Accept: application/rdf+xml'  https://staging.dracor.org/id/ger000001
curl -i  https://staging.dracor.org/id/ger000001
```

Do we need to make that more clear?

**Comment by afuetterer** [comment]
@cmil I saw, that you already submitted a fix.

I am unsure how to proceed. Should I
- edit my original issue everytime with new findings?
- open a new issue per finding? Might be overkill
- add a checklist of some sort, so that fixed findings can be seen more easily?

**Comment by afuetterer** [comment]
Something like this?

- [ ] 404 not defined in the schema: /api/corpora/{corpusname}/play/{playname}/metrics
- [ ] 404 not defined in the schema: /api/corpora/{corpusname}/play/{playname}/tei

**Comment by afuetterer** [comment]
## 401

The endpoints tagged as `admin` can return 401, which is not defined in the schema. Maybe under `components` you could add a 401 response component and reuse it with `$ref: "#/components/responses`

```yaml
components
[...]
  responses:
    '401':
      description: Authorization information is missing or invalid.
```

With the contents `{"message" : "authorization required"}`

But I am not sure if this is necessary.

**Comment by cmil** [comment]
>I am unsure how to proceed. Should I
>- edit my original issue everytime with new findings?
>- open a new issue per finding? Might be overkill
>- add a checklist of some sort, so that fixed findings can be seen more easily?

@afuetterer Thanks a lot for your debugging efforts! It helps greatly to improve the consistency and stability of the DraCor API. Could I still ask you to create individual issues for each new finding, i.e. for things like the ones you listed under its own subheading in the original post (but not for each individual endpoint that has the same problem)? Separate issues make it much easier to discuss and solve problems step by step and track the progress. Collecting several problems into one issue, even if they seem to be related, can make the discussion unnecessarily difficult and longwinded and lead to the issue staying unresolved for a long time. 

For the current issue, you can leave it as is, but please don't add new findings. I will come back to individual comments as I find time.

**Comment by afuetterer** [comment]
Closing this. Feel free to reopen.
