### ISSUE TITLE
Response of endpoint /corpora/corpusname/play/playname/metadata of single play corpora

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-api#211]
If a corpus consists of a single play only, the response of the endpoint is an object containing the metadata; but if there are more plays in a corpus the endpoint returns an array. Maybe this should always be of type array for consistency reasons? I had a script crashing because of this.

to reproduce see: https://staging.dracor.org/api/corpora/dutch/metadata

**Comment by ingoboerner** [comment]
same for https://staging.dracor.org/api/corpora/pol/metadata

**Comment by cmil** [comment]
This will be resolved with the merge of #202.
