### ISSUE TITLE
Rename `.../cast` to `.../characters`

### ISSUE THREAD

**Issue by cmil** [dracor-org/dracor-api#216]
The [/corpora/{corpusname}/plays/{playname}/cast](https://staging.dracor.org/doc/api#/public/get-cast) and [/corpora/{corpusname}/plays/{playname}/cast/csv](https://staging.dracor.org/doc/api#/public/get-cast-csv) endpoints are kind of a misnomer since these lists do not really involve any actors or cast. I suggest to replace "cast" with "characters" in order to avoid misunderstandings.

**Comment by lehkost** [comment]
Thanks for bringing this up. I totally agree, especially because we also collect all speaking characters, even if they're not mentioned in the cast list.
