### ISSUE TITLE
Implement API tests using Schemathesis

### ISSUE THREAD

**Issue by cmil** [dracor-org/dracor-api#219]
As suggested by @afuetterer (see #210 and #205) we could automate testing the DraCor API using [Schemathesis](https://github.com/schemathesis/schemathesis).

**Comment by afuetterer** [comment]
Do you need help setting this up?

The author of Schemathesis actually reached out to me and implemented XML serialization. If you go for testing with Schemathesis, I would contact him and send him a big thank you.

**Comment by cmil** [comment]
@afuetterer Help is always appreciated. Maybe you can reiterate on your PR #210 which inadvertently got closed when we merged and deleted the `v1` branch. I left a comment there: https://github.com/dracor-org/dracor-api/pull/210#issuecomment-1827610721.

**Comment by afuetterer** [comment]
What should be the goal of this endeavor?

- When should tests run? During PRs, on a schedule?
- Which API should be tested? The one in production, is there a staging/testing server?
- Can a minimal version of the DraCor API be started in CI to test?
- Which tests do you want to run?

**Comment by afuetterer** [comment]
Which compose file is the correct one to choose for testing, to test the API, there is no need to spin up a frontend container, right?

And what is the current state of the API? Are there multiple versions, is there just v1 to test?

I can draft a new PR for this and we discuss further requirements in the PR?

**Comment by lehkost** [comment]
Just a quick answer (and spoiler 😊) to question 2. This Friday, we will release our API version 1.0. For some time, we will ensure that the legacy API still works, details to follow in the release notes on Friday…

**Comment by afuetterer** [comment]
Should this
https://github.com/dracor-org/dracor-api/blob/2a1e23b7f12dd94f42a2c98a7327fc8ccf320d9f/README.md?plain=1#L40

```console
curl http://localhost:8080/api/v1/info 
```

There is no service available at port 8088.

It looks like the service is running at 8080:

https://github.com/dracor-org/dracor-api/blob/2a1e23b7f12dd94f42a2c98a7327fc8ccf320d9f/compose.yml#L15
https://github.com/dracor-org/dracor-api/blob/2a1e23b7f12dd94f42a2c98a7327fc8ccf320d9f/README.md?plain=1#L36

Or am I missing something here?

**Comment by cmil** [comment]
> 1. Which compose file is the correct one to choose for testing? To test the API, there is no need to spin up a frontend container, right?

I think a dedicated compose.test.yml would probably be best. It could either override the compose.yml similar to compose.dev.yml or be completely standalone. It would not need to start a frontend, yes.

> 2. And what is the current state of the API? Are there multiple versions, is there just v1 to test?

Since the test should only test the current code, it would only test one version, the current version. The code does not implement multiple versions at the same time. The fact that there are endpoints with both /v0 and /v1 available on staging.dracor.org is achieved by running multiple instances of dracor-api of different versions.

> 3. A PR should point to main, or what is the worklow in this repo?

Yes, the PR should target the `main` branch. The workflow should probably in a `test.yml` next to the existing `.github/workflows/publish_image_to_dockerhub.yml`.

> I can draft a new PR for this, and we discuss further requirements in the PR?

That would be great. :)

**Comment by cmil** [comment]
@afuetterer The URL http://localhost:8088/api/v1/info is actually served by the frontend service which provides a proxy to the actual restxq interface of the eXist database. The latter is available under http://localhost:8080/exist/restxq/... So instead of http://localhost:8088/api/v1/info you can directly access the eXist endpoint at http://localhost:8080/exist/restxq/v1/info. Think of http://localhost:8088/api/v1 and http://localhost:8080/exist/restxq/v1 as different base URLs to prepend to the paths in api.yml.

**Comment by afuetterer** [comment]
You could either create a `compose.test.yml` file, that overrides/removes the frontend service like this:

```yaml
services:
  frontend:
```

Or I could start only the needed services in the PR like this:

```console
docker compose up api fuseki metrics
```

You said these are all the services needed, yes?

This would not start the frontend service. But that means http://localhost:8088/api/v1/info is not available.

So http://localhost:8080/exist/restxq/v1/info is the API?

If the 8088 is better to test, the frontend service can be started as well, I guess.

**Comment by cmil** [comment]
With #220 merged, this can be closed. Thanks again @afuetterer!
