### ISSUE TITLE
Don't count acts or scene in an appendix

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-api#260]
For example, [this play](https://dracor.org/id/gersh000031) provides the structure of the play in the appendix, [see here](https://github.com/dracor-org/gershdracor/blob/9b57c42f6fae227c19cc77079f29561529697584/tei/perikles-fuerst-von-tyrus.xml#L5475).

In the metadata file, this play ends up having 10 acts (instead of just 5).

**Comment by cmil** [comment]
The appendix for the play in question should be moved out of the `body` element and into a `back` element, see https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-back.html.

**Comment by lehkost** [comment]
Thanks, that makes sense, will do that.

**Comment by lehkost** [comment]
Ok done, [see here](https://github.com/dracor-org/gershdracor/blob/a1d0c6e5a4629a4e1c6e23bd5e4d8bbd520c24a3/tei/perikles-fuerst-von-tyrus.xml#L5491). But this didn't solve the problem, we're still at 10 acts for "Perikles" in the metadata table.
