### ISSUE TITLE
Connection to Voyant Tools

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-api#265]
Find out why it does not work to directly import DraCor Data into Voyant Tools by providing the link to the API output, see also
https://github.com/EcoCor/ecocor-api/issues/1

**Comment by cmil** [comment]
It actually does work: https://voyant-tools.org/?view=corpusset&stopList=stop.de.german.txt&input=https://staging.dracor.org/api/v1/corpora/ger/plays/lessing-emilia-galotti/spoken-text

See https://github.com/EcoCor/ecocor-api/issues/1#issuecomment-2408132515.

**Comment by ingoboerner** [comment]
OK, wow, that's great news. Was an easy fix ;)

**Comment by ingoboerner** [comment]
Do you think we should include a link somewhere in the frontend, as for example the  DTA does (e.g. https://www.deutschestextarchiv.de/book/show/abelinus_theatrum_1635)?

**Comment by cmil** [comment]
> Do you think we should include a link somewhere in the frontend, as for example the DTA does (e.g. https://www.deutschestextarchiv.de/book/show/abelinus_theatrum_1635)?

Yes, that would probably be nice. The question would be where and with which parameters. And only with `spoken-text` or other resources as well? Maybe you, @ingoboerner and @lehkost could create a ticket in `dracor-frontend` detailing the feature.

**Comment by cmil** [comment]
@ingoboerner, @lehkost please edit the description for dracor-org/dracor-frontend#310.
