### ISSUE TITLE
response code 200 for /id/{id} is not documented

### ISSUE THREAD

**Issue by hsluytergaethje** [dracor-org/dracor-api#276]
For the endpoint `/id/{id}` the response codes 300 and 404 are documented, but the reponse code 200 does not seem to be documented. This should be added.

**Comment by hsluytergaethje** [comment]
I correct my statement above: As the endpoint is a redirect, it does not return the response code 200. 
In the documentation of the API in the "try it out" section, the redirect is followed, therefore the response body is an HTML-Document. (The curl command does not match the response body, as the -L flag is missing).
To me it would be clearer what the endpoint does if the redirect wasn't followed and only the response header was displayed.

**Comment by cmil** [comment]
The `/id/{id}` endpoint does not have a 200 response. For existing IDs it always responds with a redirect, for unknown IDs with a 404 error.

The problem in the Swagger UI that renders our OpenAPI document is that it follows that redirect and actually performs a second request which then results in the HTML response with code 200. This is due the `fetch` API in browsers enforcing atomic redirects for security reasons (see https://fetch.spec.whatwg.org/#atomic-http-redirect-handling). This seems to be a known issue in Swagger UI and they seem to have concluded they can do nothing about it: https://github.com/swagger-api/swagger-ui/issues/1569#issuecomment-390877095.
