### ISSUE TITLE
publish schema on website

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-api#29]
Schema (https://github.com/dracor-org/dracor-schema/blob/master/odd/out/dracor.rng) should be published on the DraCor website, possibly https://dracor.org/schema
Maybe generate schema from Source ODD via http://oxgarage.tei-c.org/

**Comment by cmil** [comment]
The schema is now available at https://dracor.org/schema.rng. Currently it's just a copy of https://github.com/dracor-org/dracor-schema/blob/master/odd/out/dracor.rng
