### ISSUE TITLE
Export metadata as both csv and json

### ISSUE THREAD

**Issue by IraPS** [dracor-org/dracor-api#30]

**Comment by cmil** [comment]
There is now an endpoint `/corpora/{corpusname}/metadata` that provides a JSON array by default and a CSV representation when requested with an `Accept: text/csv` header. See https://dracor.org/documentation/api/#/public/corpus-metadata.

The `/corpora/{corpusname}/metadata.csv` endpoint is deprecated and should no longer be used.

**Comment by lehkost** [comment]
There seems to be a mistake in the CSV output. Example from RusDraCor:

```
name,year,size,genre,averageClustering,[…]
andreyev-mysl,1914,15,tragedy,0.8108994708994709,[…]
andreyev-ne-ubiy,1913,23,0.9121040025468616,[…]
```
Explanation: There should be a ",," in line "andreyev-ne-ubiy" for empty genre value.

**Comment by cmil** [comment]
@lehkost I think the CSV is now correct. Please test and close the issue unless you find otherwise.
