### ISSUE TITLE
Provide global ID resolver

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-api#32]
```dracor.org/id/rus000001``` (etc.) should, depending on the request header:
* provide an RDF triple (if RDF is requested), or
* forward to respective play (if called via browser)

**Comment by ingoboerner** [comment]
I think so..

**Comment by cmil** [comment]
@lehkost what's the status on those IDs? As far as I can see, the TEIs don't have them yet.

**Comment by lehkost** [comment]
Good question, theoretically there's nothing that would bar us from establishing global IDs now. Existing ID patterns (sub ```<publicationStmt```) in Ger, Rus, Shake and Swe are as follows (always using random plays as example):

GER:
```<idno type="DLINA-ID">174</idno>```

RUS:
```<idno type="RusDraCor">86</idno>```

Shake:
```<idno>Mac</idno>```

SWE:
```<idno type="Dramawebben">AgrellA_Ensam</idno>```

So, Ger and Rus will be easy, they would translate to:
```<idno type="DraCor">ger000174</idno>```
```<idno type="DraCor">rus000086</idno>```

For Shake and Swe we would have to add numeric DraCor ID on top of their own ID (@mathias-goebel). They can be added as global DraCor IDs right from the start, whereas IDs for Ger and Rus have to be transformed into the new global pattern.
