### ISSUE TITLE
Add number of subgraphs per play to metadata table

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-api#57]
I am expecting that NetworkX's function [number_connected_components](https://networkx.github.io/documentation/networkx-1.9.1/reference/generated/networkx.algorithms.components.connected.number_connected_components.html) is doing just that.

For the majority of plays this value will be 1. A famous aberration will be Goethe's 1st part of *Faust* which features the unconnected *Prologue in the Theatre* and the *Walpurgis Night's Dream* scene, thus adding two subgraphs.

**Comment by cmil** [comment]
Unfortunately the method hasn't been ported to JSNetworkX yet (see `numberConnectedComponents` in http://jsnetworkx.org/api_progress.html).

**Comment by lehkost** [comment]
Ah, too bad… Wikipedia describes [an algorithm](https://en.wikipedia.org/wiki/Connected_component_(graph_theory)#Algorithms) for this, "using either breadth-first search or depth-first search". I also found [a JS implementation](https://github.com/mikolalysenko/connected-components/blob/master/cc.js) that seems to do that.

**Comment by cmil** [comment]
The number of connected components is now provided as `numConnectedComponents` in `/corpora/{corpusname}/metadata`.
