### ISSUE TITLE
Cast function of API throws servor error for some plays

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-api#63]
The play where it first turned up was Lermontov's "Maskarad":
* https://dracor.org/api/corpora/rus/play/lermontov-maskarad/cast

Looking at the error message, it seems to have to do with the way numbers are stored, probably coming from the metrics service?

Most plays seem to work fine, but there are a few others that are affected, like:
* https://dracor.org/api/corpora/rus/play/tolstoy-tsar-boris/cast
* https://dracor.org/api/corpora/rus/play/mayakovsky-misteriya-buff/cast
* https://dracor.org/api/corpora/rus/play/mayakovsky-klop/cast

**Comment by IraPS** [comment]
I noticed that all these plays have not connected graphs, so maybe that is the problem for calculating some metrics.

**Comment by lehkost** [comment]
Thx, that seems to be a hint. Same case for plays with unconnected clusters in GerDraCor:
* https://dracor.org/api/corpora/ger/play/goethe-faust-eine-tragoedie/cast
* https://dracor.org/api/corpora/ger/play/goethe-faust-der-tragoedie-zweiter-teil/cast
