### ISSUE TITLE
HTTP ERROR 500 for TEI version on https://dracor.org/ger

### ISSUE THREAD

**Issue by mhug** [dracor-org/dracor-api#64]
![Screenshot_2019-05-03_13-15-59](https://user-images.githubusercontent.com/369603/57134722-4f5d6e80-6da7-11e9-87f1-cb423c08938d.png)

**Comment by mhug** [comment]
BTW: System/Browser is Chrome on Ubuntu. And just found out: Can't reproduce problem with Firefox.

**Comment by nevmenandr** [comment]
Chrome on MacOS X Yosemite the same (Safari on the same system is ok)
Chrome on Android

**Comment by cmil** [comment]
This problem seems to be caused by a new `Accept` header in Chrome version 73 and newer. See eXist-db/exist#2679.

**Comment by cmil** [comment]
The problem has been fixed in eXist-db/exist#2673. We will upgrade our eXist instance as soon as a new version becomes available.

**Comment by cmil** [comment]
We have just upgraded to eXist-db 4.7.0, which fixes the header parsing problem.
