### ISSUE TITLE
Jena-Fuseki

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-api#77]
Setup designated Jena-Fuseki instance on dracor.org. Allow for loading RDF-data via PUT from API function.

CURL
`curl -X PUT -H Content-Type:application/rdf+xml -T file.rdf -G {base-uri}/dracor/data --data-urlencode graph=http://dracor.org/ger`

**Comment by ingoboerner** [comment]
```
<rdf:RDF xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:dracon="http://dracor.org/ontology#" xmlns:xsd="http://www.w3.org/2001/XMLSchema#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:crm="http://www.cidoc-crm.org/cidoc-crm/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about="https://dracor.org/entity/rus000118">
        <rdf:type rdf:resource="crm:E33_Linguistic_Object"/>
</rdf:Description>
</rdf:RDF>
```

**Comment by ingoboerner** [comment]
`CLEAR SILENT GRAPH <https://dracor.org/ger>` on `dracor/update` endpoint should clear the Graph

**Comment by ingoboerner** [comment]
OK, the query should look for DISTINCT ?wd only, because the labels (of course) vary..

**Comment by mathias-goebel** [comment]
turened out that we need POST as PUT will set up a new graph and rejectes data for an existing graph

**Comment by ingoboerner** [comment]
Send SPARQL unencoded in body via POST; `Content-Type` must be `application/sparql-query`

Sample Query:

```
PREFIX urn: <http://fliqz.com/>
SELECT *  FROM <urn:x-arq:UnionGraph> WHERE 
{
  ?s ?p ?o .
  
} 
LIMIT 10
```

**Comment by ingoboerner** [comment]
deleting the triples of a single play prior to the load/update operation needs 4 queries posted to `dracor/update`:

1. Remove triples of blank node used to hook wikidata-id to the creator of the play:
```
WITH <https://dracor.org/test> DELETE
	{
  		?play <http://dracor.org/ontology#has_author> ?node.
		?node ?p ?o .
	} 
WHERE 

{
  		?play <http://dracor.org/ontology#has_author> ?node.
		?node ?p ?o .
}	
```

2. remove Triples of characters of a single play:
```
WITH <https://dracor.org/test> DELETE {
    <https://dracor.org/entity/greek000026> schema:character ?character. 
    ?character ?p ?o
} WHERE {
    <https://dracor.org/entity/greek000026> schema:character ?character. 
    ?character ?p ?o
} 
```
3. remove Triples of the creation-event:

```
WITH <https://dracor.org/test> DELETE { 
    ?creation crm:P94_has_created <https://dracor.org/entity/greek000026> ;
    ?p ?o . } 
WHERE { 
    ?creation crm:P94_has_created <https://dracor.org/entity/greek000026> ;
    ?p ?o .
}
```
4. remove the remaining triples:
```
WITH <https://dracor.org/test> DELETE {
    <https://dracor.org/entity/greek000026> ?p ?o} 
WHERE {
    <https://dracor.org/entity/greek000026> ?p ?o
}
```

The problem is, that there is currently only a connection from the play to the character; so we have to remove them with a separate query. The information on the author of a play is attached at two points (1. cidoc-like via a creation event, 2. via property of the dracor-ontology `dracon:has_author`) We maybe could include it only once (1.?), this would save an update operation, but makes it probably more complicated to query the author-info. I should probably think of a way to include the inverse path of `schema:character` to connect play to character, but I'm not sure if this is possible within schema.org.

**Comment by cmil** [comment]
We have been using the triple store for four years and should have closed this long ago. For the remaining issue with updating individual plays see #233 now.
