### ISSUE TITLE
Type of maxDegreeIds

### ISSUE THREAD

**Issue by lueck** [dracor-org/dracor-api#84]
Hi, 

maybe the type of `maxDegreeIds` should be a list of strings. Now it's a string and if several characters share the maximum they are delimited by by the pipe character, `"|"`.

`"ruffus|quintus"` should be `["ruffus", "quintus"]`, I think.If  there's a single character with max degree, then this list should be of length 1, i.e. `["karl"]`, not `"karl"`. 

Regards,
Chris

**Comment by lueck** [comment]
In `/corpora/{corpusname}/play/{playname}` it is `"figure1|figure2"`.
In `/corpora/{corpusname}/play/{playname}/metrics` it is a list of strings as I would expect it to be.

**Comment by cmil** [comment]
The `/corpora/{corpusname}/play/{playname}` endpoint does not provide the `maxDegreeIds` anymore. So this issue is obsolete now.
