### ISSUE TITLE
Type of betweenness

### ISSUE THREAD

**Issue by lueck** [dracor-org/dracor-api#87]
Hi,

sometimes on the api function `/corpora/{corpusname}/play/{playname}/metrics` the type of `betweenness` is a string, but it should be an floating point number or `null`.

If found `"betweenness": "0"` on the play `alberti-brot` on some objects in `nodes`.

Regards,
Chris

**Comment by cmil** [comment]
This has probably been fixed with b1f515434adf1639fd7e98b129930e90261bec74. There are no more string values for betweenness in https://dracor.org/api/corpora/ger/play/alberti-brot/metrics. Please reopen if the problem still exists elsewhere.
