### ISSUE TITLE
Add relationList data (if available) to API functions

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-api#90]
GerDraCor has (and RusDraCor will have soon) information stored in the ```listRelation``` element. There are 4 directed and 3 undirected types of relations, **documented** in the [GerDraCor README](https://github.com/dracor-org/gerdracor#character-relations).

(Side note: SweDraCor has that info, too, but since this info is stored in Swedish and since they are using it a bit differently, we'll postpone their integration for now.)

The idea is to create an API function **/relations/csv** (and **/relations/gexf**, respectively) if (and only if, of course) this information is available. Let's take Lessing's "Emilia Galotti" as an example:

```xml
<listRelation type="personal">
  <relation name="parent_of" active="#odoardo" passive="#emilia" />
  <relation name="parent_of" active="#claudia" passive="#emilia" />
  <relation name="associated_with" active="#marinelli" passive="#der_prinz" />
  <relation name="associated_with" active="#camillo_rota" passive="#der_prinz" />
</listRelation>
```
This should be converted to this CSV list:

```csv
Source,Type,Target,Relation
odoardo,Directed,emilia,parent_of
claudia,Directed,emilia,parent_of
marinelli,Directed,der_prinz,associated_with
camillo_rota,Directed,der_prinz,associated_with
```

**Comment by cmil** [comment]
The new endpoints added in PR #96 can be tested on the https://staging.dracor.org, e.g.

https://staging.dracor.org/api/corpora/ger/play/gottsched-atalanta/relations/csv
https://staging.dracor.org/api/corpora/ger/play/gottsched-atalanta/relations/gexf

Also see individual plays for a JSON representation of relations, e.g. https://staging.dracor.org/api/corpora/ger/play/gottsched-atalanta

**Comment by lehkost** [comment]
Great work! Tried the GEXF version, had to tweak some things, but this is how it looks in Gephi:
![atalanta](https://user-images.githubusercontent.com/6539515/73436450-963ebb80-435b-11ea-8379-9073bfcb35af.png)
Things to tweak in the GEXF so that it works out of the box in Gephi:
* delete attribute ```defaultedgetype="undirected"```
* provide filename when saving, maybe with "_relations" to differentiate between co-occurrence and relational network data (e.g. "ger000252-gottsched-atalanta_relations.gexf")
* node list:
  * include number of words and person-group attributes (0 or 1), just like in the co-occurrence network data
* edge list:
  * use attribute ```label``` instead of ```relation```, e.g. ```label="siblings"```

To tweak in the CSV format:
* header: use "Label" instead of "Relation"

**Comment by cmil** [comment]
The tweaks have been made and can now be tested on staging.

**Comment by lehkost** [comment]
Just tested it, works like a charm, ***thx***!
