### ISSUE TITLE
Enhance spoken-text function with character relation data

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-api#97]
In addition to #90 and #96, we should use listRelation (where available) to enhance the ```spoken-text``` function of our API. Right now, you can limit text extraction to specific genders (male, female, unknown). We should also allow limiting text outputs according to relation properties of characters (as collected in ```<listRelation>```).

Undirected relations should be easy:
* siblings
* spouses
* friends

That way, together with the gender option, we can also limit text output to, let's say, sisters by combining gender=female and relation=siblings. Same with wifes, gender=female and relation=spouses.

Directed relations are a bit trickier since they have to point into both directions:
* parent_of
* lover_of
* related_with
* associated_with

They could end up in 8 relations to choose from:
* parent_of_active
* parent_of_passive
* lover_of_active
* lover_of_passive
* related_with_active
* related_with_passive
* associated_with_active
* associated_with_passive

If we want to limit text output to just fathers, we can choose gender=male and relation=parent_of_active. Sons would be the same gender and relation=parent_of_passive.

Once implemented, there would be a nice and simple use case: Extract all texts from fathers/mothers and sons/daugthers and use [stylo](https://cran.r-project.org/web/packages/stylo/index.html)'s ```oppose()``` function to compare vocabulary usage between parents and children.

**Comment by cmil** [comment]
An implementation has been deployed on staging.dracor.org. Please test!
